# Generated by Django 4.1 on 2022-09-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_remove_tag_articles_article_articles_alter_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='articles',
        ),
        migrations.AddField(
            model_name='tag',
            name='articles',
            field=models.ManyToManyField(related_name='scopes', through='articles.Scope', to='articles.article'),
        ),
    ]
